# Discussion

The ICT-GEP as presented in the UNESCO report on digital skills and gender lacks many of the statistical details expected in research reports of this nature. Many unknowns about the exact methods employed remain, including, but not limited to: selection criteria, consideration of outliers, and tests used to measure correlation. This re-analysis confirmed that there is a moderate, negative correlation between GGGI and the percent of women among ICT graduates. Additionally, this correlation is equivalent to the correlation produced when adjusting for the disparity between the base number of women and men graduates. A third correlation concerning the disparity between the percentage of women and men graduates who graduate from an ICT program produced a weaker correlation that is not equivalent to the other two correlation methods. 

These findings demonstrate the need for further scrutinization of the methods employed by Stoet & Geary (2018) and the UNESCO Thinkpiece. Further consensus and clarification is needed before countries accept these results as evidence for the necessity (or lack thereof) of particular policy interventions.

Future research should further investigate the validity of using the GGGI as the index of gender equality and consider alternatives other than the BIGI. Other variables besides gender equality should also be examined, such as the size of the ICT industry in each country. Future qualitative research should also be considered to avoid some of the pitfalls of this quantitative approach, like the possibility of spurious correlation. For example, interviews of women who pursued an undergraduate ICT education in an Arab State but a graduate ICT education in a European country would offer a wealth of information about the potential factors underlying the ICT-GEP hypothesis.   

## tldr;
A 2019 UNESCO report [@westBlushIfCould2019a] dedicated a think piece to the ICT Gender Equality-Paradox, displaying a paradoxical correlation— the higher the gender equality in a country, the lower the percentage of women among ICT (computer science and related subjects) graduates. The broader STEM gender-equality paradox has been challenged [@richardsonThereGenderEqualityParadox2020a] for methodological reasons, but the ICT gender-equality paradox has yet to receive similar scrutiny despite its almost parallel methods. Thus, the present analysis took a deeper look into the ICT Gender-Equality Paradox, uncovering the following:

* The UNESCO report does not provide transparency of any kind in regards to this finding (e.g., the think piece does not provide information on data cleaning/omission, descriptive or even inferential statistics). The only evidence to support their finding is a visual representation of the paradox in graph form.
* The two different, contested methods for performing the correlation test (see @richardsonThereGenderEqualityParadox2020a & @stoetGenderEqualityParadoxPart2020a) result in statistically equivalent correlations (informed by a suite of ten tests meant to test for the equality of correlations, not just the presence of two statistically significant correlation results as reported by @stoetGenderEqualityParadoxPart2020a. Thus, equal correlations result whether or not women and men's graduation base rate is taken into account. 
* A third correlation approach utilizing the disparity between the percentage of all women versus all men graduates who graduate from an ICT program is not equivalent to the aforementioned correlations, though a significant (though weaker) correlation does result.

Overall, this re-analysis points to multiple, specific weaknesses in UNESCO's reporting of an ICT Gender-Equality Paradox. In addition to these weaknesses, it remains possible that the relationship between gender equality and ICT graduation gender patterns is a spurious correlation. Further research should, therefore, be required before the ICT Gender-Equality Paradox is accepted as anything beyond a hypothesis or thought experiment.
