--- 
title: "ICT Gender-Equality Paradox Re-Analysis"
author: "Mandy Davis"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [ict-gep.bib]
citation-style: apa.csl
link-citations: yes
github-repo: mandydavis/ict-gep-re-analysis
description: "An overview and tour of the steps taken to re-analyze the ICT Gender-Equality Paradox."
---

# Introduction

In 2018, Stoet & Geary published a paper titled, "The Gender-Equality Paradox in Science, Technology, Engineering, and Mathematics Education." This paper was the first to introduce this idea of a gender-equality paradox in Science, Technology, Engineering, and Mathematics (STEM) education, and therefore gained traction in the popular media (e.g., @stoetGenderEqualityParadoxScience2018a). The STEM gender-equality paradox (STEM-GEP) represents the counter-intuitive, negative correlation between gender equality (as measured by the Global Gender Gap Index (GGGI)) and the percentage of STEM graduates who are women. That is, countries with higher gender equality tend to have a lower percentage of STEM graduates who are women.

These findings are controversial for multiple reasons. First, one can imagine how the results could used as evidence in support of politicized ideas about gender differences in the pursuit of STEM: in countries with higher gender equality, women presumably face fewer barriers to pursuing a STEM education, thus the low percentage of women STEM graduates could reflect women's choice to pursue other fields due to intrinsic factors like interest. Similarly, one might argue that the high percentage of women STEM graduates in countries with low gender equality reflects a choice to pursue STEM due to extrinsic factors like financial incentives.

Secondly, Stoet & Geary's findings are controversial due to several errors in the original paper that have since been corrected, though these changes did not impact the conclusions of the paper. Richardson et al.'s [-@richardsonThereGenderEqualityParadox2020a] commentary article illuminates two major aspects of Stoet & Geary's [-@stoetGenderEqualityParadoxScience2018a]  STEM-GEP paper that merit consideration. Richardson et al. (2020) point out that the x-axis of the STEM-GEP was misidentified. The original paper included a graph with the x-axis labeled “Women Among STEM Graduates (%)", which has been corrected to “Propensity of Women to Graduate With STEM Degrees” in the updated, 2020 paper. The new label still evokes confusion, as "propensity" could be interpreted in various ways. An even more representative x-axis label would read, "Women Among STEM Graduates (%) When Adjusted for Differences in Graduation Numbers of Men and Women." The x-axis label was changed because the data used in that correlation were not, in fact, data concerning the percent of women among STEM graduates. Rather, the data used and what Stoet & Geary (2020) now call *propensity*, is an estimate of the percentage of women among STEM graduates after adjusting for equal graduation rates among men and women. 

Richardson et al. (2020) also bring attention to the importance of which gender equality index measure is used. When re-analyzing the data with the Basic Index of Gender Equality (BIGI), the correlation between percent of women among STEM graduates and gender equality ceases to exist. However, in a reply to Richardson et al., Stoet & Geary [-@stoetGenderEqualityParadoxPart2020a] argue that the BIGI (which they developed themselves) is not an appropriate index to compare to the STEM gender data, as the BIGI measures merely well-being and not empowerment. Richardson, who directs the GenderSci Lab at Harvard University, continues to write about this controversy in a series of blog posts on the lab's website, [GenderSci Lab Blog Series](https://www.genderscilab.org/blog/the-gendersci-lab-takes-on-the-gender-equality-paradox-hypothesis-introduction-and-primer).

## The ICT Gender-Equality Paradox
Using Stoet & Geary's (2018) paper as a launching pad, the UNESCO for the EQUALS Skills Coalition dedicated part of their 2019 report on digital skills and gender [@westBlushIfCould2019a] to a Thinkpiece introducing the Information and Communication Technology (ICT) version of the STEM-GEP, henceforth the ICT-GEP. ICT refers to education programs that one might conceptualize as technology programs and broadly refers to computer science and related programs. More specifically, UNESCO provides a definition^[UNESCO defines ICT education and training as "(1) the study of techniques and acquisition of skills to produce newspapers, radio/television programmes, films/videos, recorded music and graphic reproduction with ICT; (2) the study of the design and development of computer systems and computing environments; (3) the study of using computers and computer software and applications for different purposes; and (4) the study of planning, designing, developing, maintaining and monitoring electronic equipment, machinery and systems"] outlining four categories that qualify as ICT. The ICT-GEP follows the same trend as the STEM-GEP, that is, the higher the gender equality (GGGI) of a given country, the lower the percentage of ICT graduates who are women. Though UNESCO's analysis of the ICT-GEP mostly mirrors that of Stoet & Geary (2018), the ICT-GEP has not received criticism and undergone a re-analysis like the STEM-GEP has.  

## The Present Research
The ICT-GEP Thinkpiece lacks many details concerning the method of analysis; additionally, the ICT-GEP has only been measured using one correlation strategy. The present research aims to investigate the ICT-GEP data in order to fill those methodological disclosure gaps, as well as re-analyze the ICT-GEP using two alternative methods of correlating ICT data with GGGI data. 

Following from the three related, but disparate approaches, the present research asks, for the ICT-GEP, do the three approaches result in parallel results? 